//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CaixaDBModel", "Movimento_TipoMovimento", "TipoMovimento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Caixa.DB.TipoMovimento), "Movimentos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Caixa.DB.Movimento), true)]
[assembly: EdmRelationshipAttribute("CaixaDBModel", "Permissoes_Feature", "Features", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Caixa.DB.Features), "Permissoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Caixa.DB.Permissoes), true)]
[assembly: EdmRelationshipAttribute("CaixaDBModel", "Permissao_Grupo", "GruposUsuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Caixa.DB.GruposUsuarios), "Permissoes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Caixa.DB.Permissoes), true)]
[assembly: EdmRelationshipAttribute("CaixaDBModel", "Login_GruposUsuarios", "Login", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Caixa.DB.Login), "GruposUsuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Caixa.DB.GruposUsuarios))]

#endregion

namespace Caixa.DB
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CaixaDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CaixaDBEntities object using the connection string found in the 'CaixaDBEntities' section of the application configuration file.
        /// </summary>
        public CaixaDBEntities() : base("name=CaixaDBEntities", "CaixaDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CaixaDBEntities object.
        /// </summary>
        public CaixaDBEntities(string connectionString) : base(connectionString, "CaixaDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CaixaDBEntities object.
        /// </summary>
        public CaixaDBEntities(EntityConnection connection) : base(connection, "CaixaDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Movimento> Movimentos
        {
            get
            {
                if ((_Movimentos == null))
                {
                    _Movimentos = base.CreateObjectSet<Movimento>("Movimentos");
                }
                return _Movimentos;
            }
        }
        private ObjectSet<Movimento> _Movimentos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoMovimento> TipoMovimento
        {
            get
            {
                if ((_TipoMovimento == null))
                {
                    _TipoMovimento = base.CreateObjectSet<TipoMovimento>("TipoMovimento");
                }
                return _TipoMovimento;
            }
        }
        private ObjectSet<TipoMovimento> _TipoMovimento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Features> Features
        {
            get
            {
                if ((_Features == null))
                {
                    _Features = base.CreateObjectSet<Features>("Features");
                }
                return _Features;
            }
        }
        private ObjectSet<Features> _Features;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GruposUsuarios> GruposUsuarios
        {
            get
            {
                if ((_GruposUsuarios == null))
                {
                    _GruposUsuarios = base.CreateObjectSet<GruposUsuarios>("GruposUsuarios");
                }
                return _GruposUsuarios;
            }
        }
        private ObjectSet<GruposUsuarios> _GruposUsuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Login> Login
        {
            get
            {
                if ((_Login == null))
                {
                    _Login = base.CreateObjectSet<Login>("Login");
                }
                return _Login;
            }
        }
        private ObjectSet<Login> _Login;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Permissoes> Permissoes
        {
            get
            {
                if ((_Permissoes == null))
                {
                    _Permissoes = base.CreateObjectSet<Permissoes>("Permissoes");
                }
                return _Permissoes;
            }
        }
        private ObjectSet<Permissoes> _Permissoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lembretes> Lembretes
        {
            get
            {
                if ((_Lembretes == null))
                {
                    _Lembretes = base.CreateObjectSet<Lembretes>("Lembretes");
                }
                return _Lembretes;
            }
        }
        private ObjectSet<Lembretes> _Lembretes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Movimentos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovimentos(Movimento movimento)
        {
            base.AddObject("Movimentos", movimento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoMovimento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoMovimento(TipoMovimento tipoMovimento)
        {
            base.AddObject("TipoMovimento", tipoMovimento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Features EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeatures(Features features)
        {
            base.AddObject("Features", features);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GruposUsuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGruposUsuarios(GruposUsuarios gruposUsuarios)
        {
            base.AddObject("GruposUsuarios", gruposUsuarios);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Login EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogin(Login login)
        {
            base.AddObject("Login", login);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Permissoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPermissoes(Permissoes permissoes)
        {
            base.AddObject("Permissoes", permissoes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Lembretes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLembretes(Lembretes lembretes)
        {
            base.AddObject("Lembretes", lembretes);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CaixaDBModel", Name="Features")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Features : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Features object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Features CreateFeatures(global::System.Guid id, global::System.String descricao)
        {
            Features features = new Features();
            features.Id = id;
            features.Descricao = descricao;
            return features;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CaixaDBModel", "Permissoes_Feature", "Permissoes")]
        public EntityCollection<Permissoes> Permissoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Permissoes>("CaixaDBModel.Permissoes_Feature", "Permissoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Permissoes>("CaixaDBModel.Permissoes_Feature", "Permissoes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CaixaDBModel", Name="GruposUsuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GruposUsuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GruposUsuarios object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        public static GruposUsuarios CreateGruposUsuarios(global::System.Guid id, global::System.String nome, global::System.Boolean ativo)
        {
            GruposUsuarios gruposUsuarios = new GruposUsuarios();
            gruposUsuarios.Id = id;
            gruposUsuarios.Nome = nome;
            gruposUsuarios.Ativo = ativo;
            return gruposUsuarios;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CaixaDBModel", "Permissao_Grupo", "Permissoes")]
        public EntityCollection<Permissoes> Permissoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Permissoes>("CaixaDBModel.Permissao_Grupo", "Permissoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Permissoes>("CaixaDBModel.Permissao_Grupo", "Permissoes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CaixaDBModel", "Login_GruposUsuarios", "Login")]
        public EntityCollection<Login> Logins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Login>("CaixaDBModel.Login_GruposUsuarios", "Login");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Login>("CaixaDBModel.Login_GruposUsuarios", "Login", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CaixaDBModel", Name="Lembretes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lembretes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lembretes object.
        /// </summary>
        /// <param name="texto">Initial value of the Texto property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        public static Lembretes CreateLembretes(global::System.String texto, global::System.Guid id)
        {
            Lembretes lembretes = new Lembretes();
            lembretes.Texto = texto;
            lembretes.Id = id;
            return lembretes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CaixaDBModel", Name="Login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Login object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        public static Login CreateLogin(global::System.Guid id, global::System.String username, global::System.String password, global::System.Boolean ativo)
        {
            Login login = new Login();
            login.Id = id;
            login.Username = username;
            login.Password = password;
            login.Ativo = ativo;
            return login;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CaixaDBModel", "Login_GruposUsuarios", "GruposUsuarios")]
        public EntityCollection<GruposUsuarios> GruposUsuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GruposUsuarios>("CaixaDBModel.Login_GruposUsuarios", "GruposUsuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GruposUsuarios>("CaixaDBModel.Login_GruposUsuarios", "GruposUsuarios", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CaixaDBModel", Name="Movimento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movimento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Movimento object.
        /// </summary>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tipoMovimento">Initial value of the TipoMovimento property.</param>
        public static Movimento CreateMovimento(global::System.String descricao, global::System.Double valor, global::System.DateTime data, global::System.Guid id, global::System.Guid tipoMovimento)
        {
            Movimento movimento = new Movimento();
            movimento.Descricao = descricao;
            movimento.Valor = valor;
            movimento.Data = data;
            movimento.Id = id;
            movimento.TipoMovimento = tipoMovimento;
            return movimento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Double _Valor;
        partial void OnValorChanging(global::System.Double value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacao
        {
            get
            {
                return _Observacao;
            }
            set
            {
                OnObservacaoChanging(value);
                ReportPropertyChanging("Observacao");
                _Observacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacao");
                OnObservacaoChanged();
            }
        }
        private global::System.String _Observacao;
        partial void OnObservacaoChanging(global::System.String value);
        partial void OnObservacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TipoMovimento
        {
            get
            {
                return _TipoMovimento;
            }
            set
            {
                OnTipoMovimentoChanging(value);
                ReportPropertyChanging("TipoMovimento");
                _TipoMovimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoMovimento");
                OnTipoMovimentoChanged();
            }
        }
        private global::System.Guid _TipoMovimento;
        partial void OnTipoMovimentoChanging(global::System.Guid value);
        partial void OnTipoMovimentoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CaixaDBModel", "Movimento_TipoMovimento", "TipoMovimento")]
        public TipoMovimento Tipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoMovimento>("CaixaDBModel.Movimento_TipoMovimento", "TipoMovimento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoMovimento>("CaixaDBModel.Movimento_TipoMovimento", "TipoMovimento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoMovimento> TipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoMovimento>("CaixaDBModel.Movimento_TipoMovimento", "TipoMovimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoMovimento>("CaixaDBModel.Movimento_TipoMovimento", "TipoMovimento", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CaixaDBModel", Name="Permissoes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Permissoes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Permissoes object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="id_Feature">Initial value of the Id_Feature property.</param>
        /// <param name="id_Grupo">Initial value of the Id_Grupo property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        public static Permissoes CreatePermissoes(global::System.Guid id, global::System.Guid id_Feature, global::System.Guid id_Grupo, global::System.Boolean ativo)
        {
            Permissoes permissoes = new Permissoes();
            permissoes.ID = id;
            permissoes.Id_Feature = id_Feature;
            permissoes.Id_Grupo = id_Grupo;
            permissoes.Ativo = ativo;
            return permissoes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id_Feature
        {
            get
            {
                return _Id_Feature;
            }
            set
            {
                OnId_FeatureChanging(value);
                ReportPropertyChanging("Id_Feature");
                _Id_Feature = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Feature");
                OnId_FeatureChanged();
            }
        }
        private global::System.Guid _Id_Feature;
        partial void OnId_FeatureChanging(global::System.Guid value);
        partial void OnId_FeatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id_Grupo
        {
            get
            {
                return _Id_Grupo;
            }
            set
            {
                OnId_GrupoChanging(value);
                ReportPropertyChanging("Id_Grupo");
                _Id_Grupo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Grupo");
                OnId_GrupoChanged();
            }
        }
        private global::System.Guid _Id_Grupo;
        partial void OnId_GrupoChanging(global::System.Guid value);
        partial void OnId_GrupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CaixaDBModel", "Permissoes_Feature", "Features")]
        public Features Features
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Features>("CaixaDBModel.Permissoes_Feature", "Features").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Features>("CaixaDBModel.Permissoes_Feature", "Features").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Features> FeaturesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Features>("CaixaDBModel.Permissoes_Feature", "Features");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Features>("CaixaDBModel.Permissoes_Feature", "Features", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CaixaDBModel", "Permissao_Grupo", "GruposUsuarios")]
        public GruposUsuarios GruposUsuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GruposUsuarios>("CaixaDBModel.Permissao_Grupo", "GruposUsuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GruposUsuarios>("CaixaDBModel.Permissao_Grupo", "GruposUsuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GruposUsuarios> GruposUsuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GruposUsuarios>("CaixaDBModel.Permissao_Grupo", "GruposUsuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GruposUsuarios>("CaixaDBModel.Permissao_Grupo", "GruposUsuarios", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CaixaDBModel", Name="TipoMovimento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoMovimento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoMovimento object.
        /// </summary>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        public static TipoMovimento CreateTipoMovimento(global::System.String descricao, global::System.Guid id)
        {
            TipoMovimento tipoMovimento = new TipoMovimento();
            tipoMovimento.Descricao = descricao;
            tipoMovimento.Id = id;
            return tipoMovimento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CaixaDBModel", "Movimento_TipoMovimento", "Movimentos")]
        public EntityCollection<Movimento> Movimentos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimento>("CaixaDBModel.Movimento_TipoMovimento", "Movimentos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimento>("CaixaDBModel.Movimento_TipoMovimento", "Movimentos", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
